### ISSUE TITLE
demo errors out in Matlab R2022b Update 6

### ISSUE THREAD

**Issue by shah-aditya** [suever/MarkdownPanel#2]
I ran `MarkdownPanel.demo` and it errored out. 

> >> MarkdownPanel.demo
> Warning: JAVACOMPONENT will be removed in a future release. For more information see UI
> Alternatives for MATLAB Apps on mathworks.com. 
> > In javacomponent (line 94)
> In MarkdownPanel.demo (line 400) 
> Warning: JAVACOMPONENT will be removed in a future release. For more information see UI
> Alternatives for MATLAB Apps on mathworks.com. 
> > In javacomponent (line 94)
> In MarkdownPanel (line 131)
> In MarkdownPanel.demo (line 405) 
> **Error using MarkdownPanel/refresh
> Java exception occurred:
> java.lang.UnsupportedOperationException**
> 
> 	at
>     com.mathworks.mlwidgets.html.HTMLRendererSupport.executeScript(HTMLRendererSupport.java:49)
> 
> 	at com.mathworks.mlwidgets.html.HTMLRenderer.executeScript(HTMLRenderer.java:875)
> 
> 	at
>     com.mathworks.mlwidgets.html.HtmlComponentAdapter.executeScript(HtmlComponentAdapter.java:143)
> 
> Error in MarkdownPanel/set.Options (line 327)
>             self.refresh(true);
> 
> Error in MarkdownPanel (line 158)
>             self.Options = struct(...
> 
> Error in MarkdownPanel.demo (line 405)
>             panel = MarkdownPanel( ...
 

ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.13.0.2320565 (R2022b) Update 6
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 19045)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.13        (R2022b)

**Comment by suever** [comment]
I just released v2.2.0 which should work on newer versions of MATLAB. Let me know if it works for you, thanks!

**Comment by suever** [comment]
Going to go ahead and close this issue. Feel free to open if the problem still exists!
